## Lab-data-cleaning-and-wrangling

In [1]:
# Import the necessary libraries if you are starting a new notebook

import pandas as pd
import numpy as np
import datetime
import warnings
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
warnings.filterwarnings('ignore')

In [2]:
data_cat=pd.read_csv('../lab-data-cleaning-and-wrangling/files_for_lab/Data_Categorical.csv')
Continious_df=pd.read_csv('../lab-data-cleaning-and-wrangling/files_for_lab/Data_Continious.csv') 
Discrete_df=pd.read_csv('../lab-data-cleaning-and-wrangling/files_for_lab/Data_Discrete.csv')

In [3]:
# We will start with removing outliers. So far, we have discussed different methods to remove outliers. 
# Use the one you feel more comfortable with, define a function for that. 
# Use the function to remove the outliers and apply it to the dataframe.
Data_concat = pd.concat([Continious_df, Discrete_df, data_cat], axis=1)
Data_concat

,customer_lifetime_value,income,monthly_premium_auto,months_since_last_claim,months_since_policy_inception,total_claim_amount,effective_to_date,number_of_open_complaints,number_of_policies,state,response,coverage,education,employmentstatus,gender,location_code,marital_status,policy_type,policy,renew_offer_type,sales_channel,vehicle_class,vehicle_size
0,2763.519279,56274,69,32,5,384.811147,20110224,0,1,Washington,No,Basic,Bachelor,Employed,F,Suburban,Married,Corporate Auto,Corporate L3,Offer1,Agent,Two-Door Car,Medsize
1,6979.535903,0,94,13,42,1131.464935,20110131,0,8,Arizona,No,Extended,Bachelor,Unemployed,F,Suburban,Single,Personal Auto,Personal L3,Offer3,Agent,Four-Door Car,Medsize
2,12887.431650,48767,108,18,38,566.472247,20110219,0,2,Nevada,No,Premium,Bachelor,Employed,F,Suburban,Married,Personal Auto,Personal L3,Offer1,Agent,Two-Door Car,Medsize
3,7645.861827,0,106,18,65,529.881344,20110120,0,7,California,No,Basic,Bachelor,Unemployed,M,Suburban,Married,Corporate Auto,Corporate L2,Offer1,Call Center,SUV,Medsize
4,2813.692575,43836,73,12,44,138.130879,20110203,0,1,Washington,No,Basic,Bachelor,Employed,M,Rural,Single,Personal Auto,Personal L1,Offer1,Agent,Four-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9129,23405.987980,71941,73,18,89,198.234764,20110210,0,2,California,No,Basic,Bachelor,Employed,M,Urban,Married,Personal Auto,Personal L1,Offer2,Web,Four-Door Car,Medsize
9130,3096.511217,21604,79,14,28,379.200000,20110212,0,1,California,Yes,Extended,College,Employed,F,Suburban,Divorced,Corporate Auto,Corporate L3,Offer1,Branch,Four-Door Car,Medsize
9131,8163.890428,0,85,9,37,790.784983,20110206,3,2,California,No,Extended,Bachelor,Unemployed,M,Suburban,Single,Corporate Auto,Corporate L2,Offer1,Branch,Four-Door Car,Medsize
9132,7524.442436,21941,96,34,3,691.200000,20110203,0,3,California,No,Extended,College,Employed,M,Suburban,Married,Personal Auto,Personal L2,Offer3,Branch,Four-Door Car,Large
9133,2611.836866,0,77,3,90,369.600000,20110214,0,1,California,No,Extended,College,Unemployed,M,Suburban,Single,Corporate Auto,Corporate L3,Offer4,Call Center,Two-Door Car,Medsize

In [4]:
# We will start with removing outliers. So far, we have discussed different methods to remove outliers.
# Use the one you feel more comfortable with, define a function for that.
# Use the function to remove the outliers and apply it to the dataframe.
df=Continious_df
def remove_outliers(df, threshold=1.5, in_columns=df.select_dtypes(np.number).columns, skip_columns=[]):
    #skip_columns 
    for column in in_columns:
        if column not in skip_columns:
            upper = np.percentile(df[column],75)
            lower = np.percentile(df[column],25)
            iqr = upper - lower
            upper_limit = upper + threshold * iqr
            lower_limit = lower - threshold * iqr
            df = df[(df[column]>lower_limit) & (df[column]<upper_limit)]
    return df

In [5]:
Data_no_outliers=remove_outliers(Data_concat, threshold=1.5, skip_columns=['effective_to_date', 'number_of_open_complaints', 'state', 'response', 'coverage', 'education', 'employmentstatus', 'gender', 'location_code', 'marital_status', 'policy_type', 'policy' ,'renew_offer_type', 'sales_channel', 'vehicle_class', 'vehicle_size'])

In [6]:
# Create a copy of the dataframe for the data wrangling.
Data1=Data_no_outliers.copy()

In [7]:
# Numerical
# Normalize the continuous variables. You can use any one method you want. (Numerical)
def normalize(df):
    result = df.copy()
    for feature_name in df.select_dtypes(np.number).columns:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result

In [8]:
result= normalize(Data1)
result

,customer_lifetime_value,income,monthly_premium_auto,months_since_last_claim,months_since_policy_inception,total_claim_amount,effective_to_date,number_of_open_complaints,number_of_policies,state,response,coverage,education,employmentstatus,gender,location_code,marital_status,policy_type,policy,renew_offer_type,sales_channel,vehicle_class,vehicle_size
0,0.059651,0.562847,0.076923,0.914286,0.050505,0.417151,0.968504,0.0,0.000,Washington,No,Basic,Bachelor,Employed,F,Suburban,Married,Corporate Auto,Corporate L3,Offer1,Agent,Two-Door Car,Medsize
2,0.757387,0.487763,0.451923,0.514286,0.383838,0.614130,0.929134,0.0,0.125,Nevada,No,Premium,Bachelor,Employed,F,Suburban,Married,Personal Auto,Personal L3,Offer1,Agent,Two-Door Car,Medsize
3,0.396140,0.000000,0.432692,0.514286,0.656566,0.574454,0.149606,0.0,0.750,California,No,Basic,Bachelor,Unemployed,M,Suburban,Married,Corporate Auto,Corporate L2,Offer1,Call Center,SUV,Medsize
4,0.063109,0.438443,0.115385,0.342857,0.444444,0.149671,0.803150,0.0,0.000,Washington,No,Basic,Bachelor,Employed,M,Rural,Single,Personal Auto,Personal L1,Offer1,Agent,Four-Door Car,Medsize
5,0.438211,0.629140,0.076923,0.400000,0.949495,0.172715,0.188976,0.0,0.125,Oregon,Yes,Basic,Bachelor,Employed,F,Rural,Married,Personal Auto,Personal L3,Offer2,Web,Two-Door Car,Medsize
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9128,0.151788,0.477701,0.413462,0.457143,0.585859,0.586816,0.039370,0.0,0.000,California,No,Premium,College,Employed,F,Suburban,Single,Personal Auto,Personal L2,Offer1,Branch,Four-Door Car,Large
9130,0.082600,0.216081,0.173077,0.400000,0.282828,0.411067,0.874016,0.0,0.000,California,Yes,Extended,College,Employed,F,Suburban,Divorced,Corporate Auto,Corporate L3,Offer1,Branch,Four-Door Car,Medsize
9131,0.431842,0.000000,0.230769,0.257143,0.373737,0.857357,0.826772,0.6,0.125,California,No,Extended,Bachelor,Unemployed,M,Suburban,Single,Corporate Auto,Corporate L2,Offer1,Branch,Four-Door Car,Medsize
9132,0.387772,0.219452,0.336538,0.971429,0.030303,0.749375,0.803150,0.0,0.250,California,No,Extended,College,Employed,M,Suburban,Married,Personal Auto,Personal L2,Offer3,Branch,Four-Door Car,Large
9133,0.049197,0.000000,0.153846,0.085714,0.909091,0.400657,0.889764,0.0,0.000,California,No,Extended,College,Unemployed,M,Suburban,Single,Corporate Auto,Corporate L3,Offer4,Call Center,Two-Door Car,Medsize

In [9]:
#Encoding

# Ordinal to coverage
# Ordinal to employmentstatus
# Ordinal to location code
# Ordinal vehicle size

# One hot to state
# One hot to marital status
# One hot to policy type
# One hot to policy
# One hot to renew offercustomer_df
# One hot to sales channel
# One hot vehicle class

In [10]:
coverage_ordinal=[]
for i in result['coverage']:
    if i =='Basic':
        coverage_ordinal.append(0)
    elif i == 'Extended':
        coverage_ordinal.append(1)
    else:
        coverage_ordinal.append(2)

result['coverage']=coverage_ordinal

result['coverage']

0       0
2       2
3       0
4       0
5       0
       ..
9128    2
9130    1
9131    1
9132    1
9133    1
Name: coverage, Length: 7789, dtype: int64

In [11]:
employmentstatus_ordinal=[]
for i in result['employmentstatus']:
    if i =='Retired':
        employmentstatus_ordinal.append(0)
    elif i == 'Disabled':
        employmentstatus_ordinal.append(1)
    elif i == 'Medical Leave':
        employmentstatus_ordinal.append(2)
    elif i == 'Unemployed':
        employmentstatus_ordinal.append(3)
    else:
        employmentstatus_ordinal.append(4)

result['employmentstatus']=employmentstatus_ordinal
result['employmentstatus']

0       4
2       4
3       3
4       4
5       4
       ..
9128    4
9130    4
9131    3
9132    4
9133    3
Name: employmentstatus, Length: 7789, dtype: int64

In [12]:
location_code_ordinal=[]
for i in result['location_code']:
    if i =='Rural':
        location_code_ordinal.append(0)
    elif i == 'Suburban':
        location_code_ordinal.append(1)
    else:
        location_code_ordinal.append(2)

result['location_code']=location_code_ordinal

result['location_code']

0       1
2       1
3       1
4       0
5       0
       ..
9128    1
9130    1
9131    1
9132    1
9133    1
Name: location_code, Length: 7789, dtype: int64

In [13]:
vehicle_size_ordinal=[]
for i in result['vehicle_size']:
    if i =='Small':
        vehicle_size_ordinal.append(0)
    elif i == 'Medsize':
        vehicle_size_ordinal.append(1)
    else:
        vehicle_size_ordinal.append(2)

result['vehicle_size']=vehicle_size_ordinal
result['vehicle_size']

0       1
2       1
3       1
4       1
5       1
       ..
9128    2
9130    1
9131    1
9132    2
9133    1
Name: vehicle_size, Length: 7789, dtype: int64

In [14]:
education_ordinal=[]
for i in result['education']:
    if i =='High School or Below':
        education_ordinal.append(0)
    elif i == 'College':
        education_ordinal.append(1)
    elif i == 'Bachelor':
        education_ordinal.append(2)
    elif i == 'Master':
        education_ordinal.append(3)
    else:
        education_ordinal.append(4)

result['education']=education_ordinal
result['education']

0       2
2       2
3       2
4       2
5       2
       ..
9128    1
9130    1
9131    2
9132    1
9133    1
Name: education, Length: 7789, dtype: int64

Index(['response', 'gender', 'marital_status', 'policy_type', 'policy',
       'renew_offer_type', 'sales_channel', 'vehicle_class'],
      dtype='object')

In [17]:
# The time variable can be useful. 
# Try to transform its data into a useful one. Hint: Day week and month as integers might be useful.

,customer_lifetime_value,income,monthly_premium_auto,months_since_last_claim,months_since_policy_inception,total_claim_amount,effective_to_date,number_of_open_complaints,number_of_policies,state,response,coverage,education,employmentstatus,gender,location_code,marital_status,policy_type,policy,renew_offer_type,sales_channel,vehicle_class,vehicle_size
0,0.059651,0.562847,0.076923,0.914286,0.050505,0.417151,0.968504,0.0,0.000,Washington,No,0,2,4,F,1,Married,Corporate Auto,Corporate L3,Offer1,Agent,Two-Door Car,1
2,0.757387,0.487763,0.451923,0.514286,0.383838,0.614130,0.929134,0.0,0.125,Nevada,No,2,2,4,F,1,Married,Personal Auto,Personal L3,Offer1,Agent,Two-Door Car,1
3,0.396140,0.000000,0.432692,0.514286,0.656566,0.574454,0.149606,0.0,0.750,California,No,0,2,3,M,1,Married,Corporate Auto,Corporate L2,Offer1,Call Center,SUV,1
4,0.063109,0.438443,0.115385,0.342857,0.444444,0.149671,0.803150,0.0,0.000,Washington,No,0,2,4,M,0,Single,Personal Auto,Personal L1,Offer1,Agent,Four-Door Car,1
5,0.438211,0.629140,0.076923,0.400000,0.949495,0.172715,0.188976,0.0,0.125,Oregon,Yes,0,2,4,F,0,Married,Personal Auto,Personal L3,Offer2,Web,Two-Door Car,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9128,0.151788,0.477701,0.413462,0.457143,0.585859,0.586816,0.039370,0.0,0.000,California,No,2,1,4,F,1,Single,Personal Auto,Personal L2,Offer1,Branch,Four-Door Car,2
9130,0.082600,0.216081,0.173077,0.400000,0.282828,0.411067,0.874016,0.0,0.000,California,Yes,1,1,4,F,1,Divorced,Corporate Auto,Corporate L3,Offer1,Branch,Four-Door Car,1
9131,0.431842,0.000000,0.230769,0.257143,0.373737,0.857357,0.826772,0.6,0.125,California,No,1,2,3,M,1,Single,Corporate Auto,Corporate L2,Offer1,Branch,Four-Door Car,1
9132,0.387772,0.219452,0.336538,0.971429,0.030303,0.749375,0.803150,0.0,0.250,California,No,1,1,4,M,1,Married,Personal Auto,Personal L2,Offer3,Branch,Four-Door Car,2
9133,0.049197,0.000000,0.153846,0.085714,0.909091,0.400657,0.889764,0.0,0.000,California,No,1,1,3,M,1,Single,Corporate Auto,Corporate L3,Offer4,Call Center,Two-Door Car,1

In [18]:
result2 = pd.get_dummies(result, columns=['response','gender','state', 'marital_status','policy_type', 'policy','renew_offer_type', 'sales_channel','vehicle_class']) 
result2

,customer_lifetime_value,income,monthly_premium_auto,months_since_last_claim,months_since_policy_inception,total_claim_amount,effective_to_date,number_of_open_complaints,number_of_policies,coverage,education,employmentstatus,location_code,vehicle_size,response_No,response_Yes,gender_F,gender_M,state_Arizona,state_California,state_Nevada,state_Oregon,state_Washington,marital_status_Divorced,marital_status_Married,marital_status_Single,policy_type_Corporate Auto,policy_type_Personal Auto,policy_type_Special Auto,policy_Corporate L1,policy_Corporate L2,policy_Corporate L3,policy_Personal L1,policy_Personal L2,policy_Personal L3,policy_Special L1,policy_Special L2,policy_Special L3,renew_offer_type_Offer1,renew_offer_type_Offer2,renew_offer_type_Offer3,renew_offer_type_Offer4,sales_channel_Agent,sales_channel_Branch,sales_channel_Call Center,sales_channel_Web,vehicle_class_Four-Door Car,vehicle_class_SUV,vehicle_class_Sports Car,vehicle_class_Two-Door Car
0,0.059651,0.562847,0.076923,0.914286,0.050505,0.417151,0.968504,0.0,0.000,0,2,4,1,1,1,0,1,0,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1
2,0.757387,0.487763,0.451923,0.514286,0.383838,0.614130,0.929134,0.0,0.125,2,2,4,1,1,1,0,1,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1
3,0.396140,0.000000,0.432692,0.514286,0.656566,0.574454,0.149606,0.0,0.750,0,2,3,1,1,1,0,0,1,0,1,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0
4,0.063109,0.438443,0.115385,0.342857,0.444444,0.149671,0.803150,0.0,0.000,0,2,4,0,1,1,0,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0
5,0.438211,0.629140,0.076923,0.400000,0.949495,0.172715,0.188976,0.0,0.125,0,2,4,0,1,0,1,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9128,0.151788,0.477701,0.413462,0.457143,0.585859,0.586816,0.039370,0.0,0.000,2,1,4,1,2,1,0,1,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0
9130,0.082600,0.216081,0.173077,0.400000,0.282828,0.411067,0.874016,0.0,0.000,1,1,4,1,1,0,1,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0
9131,0.431842,0.000000,0.230769,0.257143,0.373737,0.857357,0.826772,0.6,0.125,1,2,3,1,1,1,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0
9132,0.387772,0.219452,0.336538,0.971429,0.030303,0.749375,0.803150,0.0,0.250,1,1,4,1,2,1,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0
9133,0.049197,0.000000,0.153846,0.085714,0.909091,0.400657,0.889764,0.0,0.000,1,1,3,1,1,1,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1